import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import SeverityPill from '../../components/SeverityPill'
import { assetUrl } from '../../api/assetUrl'
import { fetchWorkOrder, generateWorkOrder } from '../../api/workOrderApi'

function formatDateTime(iso) {
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

export default function WorkOrderPage() {
  const { id } = useParams()
  const [workOrder, setWorkOrder] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const load = useCallback(() => {
    setLoading(true)
    fetchWorkOrder(id)
      .then(setWorkOrder)
      .catch(() =>
        generateWorkOrder(id)
          .then(setWorkOrder)
          .catch((err) => setError(err.friendlyMessage || 'Failed to generate the work order.'))
      )
      .finally(() => setLoading(false))
  }, [id])

  useEffect(() => {
    load()
  }, [load])

  if (loading) {
    return <div className="card p-4 text-center text-muted-app">Preparing work order…</div>
  }

  if (error || !workOrder) {
    return <div className="alert alert-danger">{error || 'Work order not available.'}</div>
  }

  const { report } = workOrder

  return (
    <div className="work-order-page">
      <div className="d-flex justify-content-between align-items-center mb-4 no-print flex-wrap gap-2">
        <Link to="/admin/repairs" className="btn btn-outline-secondary btn-sm">
          ← Back to Repair Management
        </Link>
        <button type="button" className="btn btn-app-primary" onClick={() => window.print()}>
          Print work order
        </button>
      </div>

      <div className="card p-4 p-md-5 work-order-sheet">
        <div className="d-flex justify-content-between align-items-start mb-4 pb-3 border-bottom">
          <div>
            <div className="fw-bold h5 mb-1">RoadVision AI — Maintenance Work Order</div>
            <div className="small text-muted-app">Work Order ID: {workOrder.id}</div>
          </div>
          <div className="text-end small text-muted-app">
            Generated by {workOrder.generatedByName}
            <br />
            {formatDateTime(workOrder.generatedAt)}
          </div>
        </div>

        <div className="row g-4">
          <div className="col-md-5">
            <img src={assetUrl(report.imageUrl)} alt="Road damage" className="work-order-sheet__image" />
          </div>

          <div className="col-md-7">
            <h2 className="h6 fw-semibold mb-3">Detection Result</h2>
            <dl className="detail-list mb-4">
              <dt>Damage type</dt>
              <dd>{report.damageType.replace('_', ' ')}</dd>
              <dt>Severity</dt>
              <dd>
                <SeverityPill severity={report.severity} />
              </dd>
              <dt>AI confidence</dt>
              <dd>{report.confidenceScore}%</dd>
              <dt>Location</dt>
              <dd>
                {report.addressText || 'Not specified'}
                {report.latitude && report.longitude ? ` (${report.latitude}, ${report.longitude})` : ''}
              </dd>
            </dl>

            <h2 className="h6 fw-semibold mb-3">Repair Plan</h2>
            <dl className="detail-list mb-0">
              <dt>Repair priority</dt>
              <dd>{report.repairPriority}</dd>
              <dt>Estimated cost</dt>
              <dd>₹{report.estimatedCost}</dd>
              <dt>Estimated labor</dt>
              <dd>{workOrder.estimatedLaborHours} hours</dd>
              <dt>Estimated duration</dt>
              <dd>{workOrder.estimatedDurationDays} day(s)</dd>
            </dl>
          </div>
        </div>

        <h2 className="h6 fw-semibold mt-4 mb-3">Materials Required</h2>
        <ul className="work-order-sheet__materials">
          {workOrder.materialsRequired.map((material) => (
            <li key={material}>{material}</li>
          ))}
        </ul>

        <div className="row g-4 mt-4 pt-3 border-top">
          <div className="col-6">
            <div className="small text-muted-app mb-4">Supervisor signature</div>
            <div className="work-order-sheet__signature" />
          </div>
          <div className="col-6">
            <div className="small text-muted-app mb-4">Date completed</div>
            <div className="work-order-sheet__signature" />
          </div>
        </div>
      </div>
    </div>
  )
}
